spring:
  datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://localhost:10000/hive_test
    username:
    password:
  aop:
    auto: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
  config:
    classpath: logback-spring.xml

hdfs:
  host: localhost
  port: 9000
  user: root
server:
  port: 8082

